/-
Copyright (c) 2023 David Loeffler. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Loeffler
-/
import Mathlib.Analysis.Fourier.AddCircle
import Mathlib.MeasureTheory.Integral.Pi

/-! # Fourier bases for products of circles of arbitrary common period

The construction generalizes Mathlib.Analysis.Fourier.AddCircleMulti from period one.
-/
noncomputable section
open scoped ComplexConjugate ENNReal
open Set Algebra Submodule MeasureTheory

namespace AddTorus
variable {T : ℝ} [Fact (0 < T)]
/-- Equip the circle with its normalized Haar measure. -/
local instance : MeasureSpace (AddCircle T) := ⟨AddCircle.haarAddCircle⟩
/-- Normalized circle volume is an additive Haar measure. -/
local instance : Measure.IsAddHaarMeasure (volume : Measure (AddCircle T)) :=
  inferInstanceAs (Measure.IsAddHaarMeasure AddCircle.haarAddCircle)
/-- Normalized circle volume has total mass one. -/
local instance : IsProbabilityMeasure (volume : Measure (AddCircle T)) :=
  inferInstanceAs (IsProbabilityMeasure AddCircle.haarAddCircle)
/-- Normalized circle volume is regular. -/
local instance : (volume : Measure (AddCircle T)).Regular := by
  change AddCircle.haarAddCircle.Regular
  unfold AddCircle.haarAddCircle
  infer_instance
variable {d : Type*} [Fintype d]

section Monomials

variable (n : d → ℤ)

/-- Exponential monomials in `d` variables. -/
def mFourier : C((d → AddCircle T), ℂ) where
  toFun x := ∏ i : d, fourier (n i) (x i)
  continuous_toFun := by fun_prop

variable {n} {x : (d → AddCircle T)}

/-- Negating a frequency conjugates its product-circle character. -/
lemma mFourier_neg : mFourier (-n) x = conj (mFourier n x) := by
  simp only [mFourier, Pi.neg_apply, fourier_neg, ContinuousMap.coe_mk, map_prod]

/-- Adding frequencies multiplies their product-circle characters. -/
lemma mFourier_add {m : d → ℤ} : mFourier (m + n) x = mFourier m x * mFourier n x := by
  simp only [mFourier, Pi.add_apply, fourier_add, ContinuousMap.coe_mk, ← Finset.prod_mul_distrib]

/-- The zero-frequency product-circle character is constant one. -/
lemma mFourier_zero : mFourier (T := T) (0 : d → ℤ) = 1 := by
  ext x
  simp only [mFourier, Pi.zero_apply, fourier_zero, Finset.prod_const_one, ContinuousMap.coe_mk,
    ContinuousMap.one_apply]

/-- Product-circle characters have unit complex norm. -/
lemma mFourier_norm : ‖mFourier (T := T) n‖ = 1 := by
  apply le_antisymm
  · refine (ContinuousMap.norm_le _ zero_le_one).mpr fun i ↦ ?_
    simp only [mFourier, fourier_apply, ContinuousMap.coe_mk, norm_prod, Circle.norm_coe,
      Finset.prod_const_one, le_rfl]
  · refine (le_of_eq ?_).trans ((mFourier n).norm_coe_le_norm fun _ ↦ 0)
    simp only [mFourier, ContinuousMap.coe_mk, fourier_eval_zero, Finset.prod_const_one,
      CStarRing.norm_one]

/-- A frequency supported in one coordinate gives the corresponding circle character. -/
lemma mFourier_single [DecidableEq d] (z : d → AddCircle T) (i : d) :
    mFourier (Pi.single i 1) z = fourier 1 (z i) := by
  simp_rw [mFourier, ContinuousMap.coe_mk]
  have := Finset.prod_mul_prod_compl {i} (fun j ↦ fourier ((Pi.single i (1 : ℤ) : d → ℤ) j) (z j))
  rw [Finset.prod_singleton, Finset.prod_congr rfl (fun j hj ↦ ?_)] at this
  · rw [← this, Finset.prod_const_one, mul_one, Pi.single_eq_same]
  · rw [Finset.mem_compl, Finset.mem_singleton] at hj
    simp only [Pi.single_eq_of_ne hj, fourier_zero]

end Monomials

section Algebra

/-- The star subalgebra of `C((d → AddCircle T), ℂ)` generated by `mFourier n` for `n ∈ ℤᵈ`. -/
def mFourierSubalgebra (d : Type*) [Fintype d] : StarSubalgebra ℂ C((d → AddCircle T), ℂ) where
  toSubalgebra := Algebra.adjoin ℂ (range mFourier)
  star_mem' := by
    change Algebra.adjoin ℂ (range mFourier) ≤ star (Algebra.adjoin ℂ (range mFourier))
    refine adjoin_le ?_
    rintro _ ⟨n, rfl⟩
    refine subset_adjoin ⟨-n, ?_⟩
    ext1 x
    simp only [mFourier_neg, starRingEnd_apply, ContinuousMap.star_apply]

/-- The star subalgebra of `C((d → AddCircle T), ℂ)` generated by `mFourier n` for `n ∈ ℤᵈ` is in
fact
the linear span of these functions. -/
theorem mFourierSubalgebra_coe :
    (mFourierSubalgebra (T := T) d).toSubalgebra.toSubmodule = span ℂ (range mFourier) := by
  apply adjoin_eq_span_of_subset
  refine .trans (fun x ↦ Submonoid.closure_induction (fun _ ↦ id) ⟨0, ?_⟩ ?_) subset_span
  · ext z
    simp only [mFourier, Pi.zero_apply, fourier_zero, Finset.prod_const, one_pow,
      ContinuousMap.coe_mk, ContinuousMap.one_apply]
  · rintro _ _ _ _ ⟨m, rfl⟩ ⟨n, rfl⟩
    refine ⟨m + n, ?_⟩
    ext z
    simp only [mFourier, Pi.add_apply, fourier_apply, fourier_add', Finset.prod_mul_distrib,
      ContinuousMap.coe_mk, ContinuousMap.mul_apply]

/-- The subalgebra of `C((d → AddCircle T), ℂ)` generated by `mFourier n` for `n ∈ ℤᵈ` separates
points. -/
theorem mFourierSubalgebra_separatesPoints : (mFourierSubalgebra (T := T) d).SeparatesPoints := by
  classical
  intro x y hxy
  rw [Ne, funext_iff, not_forall] at hxy
  obtain ⟨i, hi⟩ := hxy
  refine ⟨_, ⟨mFourier (Pi.single i 1), subset_adjoin ⟨Pi.single i 1, rfl⟩, rfl⟩, ?_⟩
  dsimp only
  rw [mFourier_single, mFourier_single, fourier_one, fourier_one, Ne, Subtype.coe_inj]
  contrapose hi
  exact AddCircle.injective_toCircle (ne_of_gt (Fact.out : (0 : ℝ) < T)) hi

/-- The subalgebra of `C((d → AddCircle T), ℂ)` generated by `mFourier n` for `n : d → ℤ` is dense.
-/
theorem mFourierSubalgebra_closure_eq_top : (mFourierSubalgebra (T := T) d).topologicalClosure =
    ⊤ :=
  ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints _
    mFourierSubalgebra_separatesPoints

/-- The linear span of the monomials `mFourier n` is dense in `C((d → AddCircle T), ℂ)`. -/
theorem span_mFourier_closure_eq_top :
    (span ℂ (range <| mFourier (T := T) (d := d))).topologicalClosure = ⊤ := by
  rw [← mFourierSubalgebra_coe]
  exact congr_arg (Subalgebra.toSubmodule <| StarSubalgebra.toSubalgebra ·)
    mFourierSubalgebra_closure_eq_top

end Algebra

section Lp

/-- The family of monomials `mFourier n`, parametrized by `n : ℤᵈ` and considered as
elements of the `Lp` space of functions `(d → AddCircle T) → ℂ`. -/
abbrev mFourierLp (p : ℝ≥0∞) [Fact (1 ≤ p)] (n : d → ℤ) :
    Lp ℂ p (volume : Measure ((d → AddCircle T))) :=
  ContinuousMap.toLp (E := ℂ) p volume ℂ (mFourier n)

/-- The `Lᵖ` Fourier vector is almost everywhere equal to its continuous character. -/
theorem coeFn_mFourierLp (p : ℝ≥0∞) [Fact (1 ≤ p)] (n : d → ℤ) :
    mFourierLp (T := T) p n =ᵐ[volume] mFourier n :=
  ContinuousMap.coeFn_toLp volume (mFourier n)

/-- For each `1 ≤ p < ∞`, the linear span of the monomials `mFourier n` is dense in the `Lᵖ` space
of functions on `(d → AddCircle T)`. -/
theorem span_mFourierLp_closure_eq_top {p : ℝ≥0∞} [Fact (1 ≤ p)] (hp : p ≠ ∞) :
    (span ℂ (range (mFourierLp (T := T) (d := d) p))).topologicalClosure = ⊤ := by
  simpa only [map_span, ContinuousLinearMap.coe_coe, ← range_comp, Function.comp_def] using
    (ContinuousMap.toLp_denseRange ℂ volume ℂ hp).topologicalClosure_map_submodule
      span_mFourier_closure_eq_top

/-- The monomials `mFourierLp 2 n` are an orthonormal set in `L²`. -/
theorem orthonormal_mFourier : Orthonormal ℂ (mFourierLp (T := T) (d := d) 2) := by
  rw [orthonormal_iff_ite]
  intro m n
  simp only [ContinuousMap.inner_toLp, ← mFourier_neg, ← mFourier_add]
  split_ifs with h
  · simpa only [h, add_neg_cancel, mFourier_zero, probReal_univ, one_smul] using!
      integral_const (α := (d → AddCircle T)) (μ := volume) (1 : ℂ)
  rw [mFourier, ContinuousMap.coe_mk, MeasureTheory.integral_fintype_prod_volume_eq_prod]
  obtain ⟨i, hi⟩ := Function.ne_iff.mp h
  apply Finset.prod_eq_zero (Finset.mem_univ i)
  simpa only [eq_false_intro hi, if_false, ContinuousMap.inner_toLp, ← fourier_neg,
    ← fourier_add] using! (orthonormal_iff_ite.mp <| orthonormal_fourier) (m i) (n i)

end Lp

section fourierCoeff

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]

/-- The `n`-th Fourier coefficient of a function `(d → AddCircle T) → E`, for `E` a complete normed
`ℂ`-vector space, defined as the integral over `(d → AddCircle T)` of `mFourier (-n) t • f t`. -/
def mFourierCoeff (f : (d → AddCircle T) → E) (n : d → ℤ) : E := ∫ t, mFourier (-n) t • f t

end fourierCoeff

section FourierL2

local notation "L²(" α ")" => Lp ℂ 2 (volume : Measure α)

/-- We define `mFourierBasis` to be a `ℤᵈ`-indexed Hilbert basis for the `L²` space of functions
on `(d → AddCircle T)`, which by definition is an isometric isomorphism from `L²((d → AddCircle T))`
to `ℓ²(ℤᵈ, ℂ)`. -/
def mFourierBasis : HilbertBasis (d → ℤ) ℂ L²((d → AddCircle T)) :=
  HilbertBasis.mk orthonormal_mFourier (span_mFourierLp_closure_eq_top (by simp)).ge

/-- The elements of the Hilbert basis `mFourierBasis` are the functions `mFourierLp 2`, i.e. the
monomials `mFourier n` on `(d → AddCircle T)` considered as elements of `L²`. -/
@[simp]
theorem coe_mFourierBasis : ⇑(mFourierBasis (T := T) (d := d)) = mFourierLp 2 :=
    HilbertBasis.coe_mk _ _

/-- Under the isometric isomorphism `mFourierBasis` from `L²((d → AddCircle T))` to `ℓ²(ℤᵈ, ℂ)`,
the `i`-th coefficient is `mFourierCoeff f i`. -/
theorem mFourierBasis_repr (f : L²((d → AddCircle T))) (i : d → ℤ) :
    mFourierBasis.repr f i = mFourierCoeff f i := by
  trans ∫ t, conj (mFourierLp 2 i t) * f t
  · rw [mFourierBasis.repr_apply_apply f i, MeasureTheory.L2.inner_def, coe_mFourierBasis]
    simp only [RCLike.inner_apply, mul_comm]
  · apply integral_congr_ae
    filter_upwards [coeFn_mFourierLp 2 i] with _ ht
    rw [ht, ← mFourier_neg, smul_eq_mul]


end FourierL2
end AddTorus
