import OperatorRidgelet.Activation
import OperatorRidgelet.Cylindrical
import OperatorRidgelet.RankOneLift
import OperatorRidgelet.OperatorValuedRidgelet
import OperatorRidgelet.ToFoML.ActivationContraction
import OperatorRidgelet.ToFoML.ProbabilisticMethod
import OperatorRidgelet.ToFoML.RidgeFeature
import OperatorRidgelet.ToFoML.RademacherSigns
import OperatorRidgelet.Network.Defs
import OperatorRidgelet.Architecture.Defs
import OperatorRidgelet.Architecture.Basic
import OperatorRidgelet.Architecture.Reduction
import OperatorRidgelet.Transform.Defs
import OperatorRidgelet.Transform.Infra
import OperatorRidgelet.Transform.Gaussian
import OperatorRidgelet.Transform.Basic
import OperatorRidgelet.Transform.Mixture
import OperatorRidgelet.FiniteDim.Defs
import OperatorRidgelet.Filters.Defs
import OperatorRidgelet.Reconstruction.Defs
import OperatorRidgelet.Reconstruction.Basic
import OperatorRidgelet.Tempered.Const
import OperatorRidgelet.Tempered.Defs
import OperatorRidgelet.Tempered.Basic
import OperatorRidgelet.Sampling.Defs
import OperatorRidgelet.Sampling.Basic
import OperatorRidgelet.Examples.Defs
import OperatorRidgelet.Examples.Basic
import OperatorRidgelet.Examples.GaussianLaw
import OperatorRidgelet.Examples.NotCylindrical
import OperatorRidgelet.Examples.OperatorLayer
import OperatorRidgelet.Examples.HingeMeasure
import OperatorRidgelet.Examples.Convolution
import OperatorRidgelet.Examples.GaussianMeasurability
import OperatorRidgelet.Examples.Dirichlet
import OperatorRidgelet.Examples.DirichletOperator
import OperatorRidgelet.Examples.LayerRidgelet
import OperatorRidgelet.Examples.SliceCoefficient
import OperatorRidgelet.Examples.SliceCoefficientVec
import OperatorRidgelet.ToMathlib.CharFunCoordinate
import OperatorRidgelet.ToMathlib.FourierEven
import OperatorRidgelet.ToMathlib.GaussianCoordinateLaw
import OperatorRidgelet.ToMathlib.GaussianFourier
import OperatorRidgelet.ToMathlib.GaussianHilbert
import OperatorRidgelet.ToMathlib.GaussianQuadraticForm
import OperatorRidgelet.ToMathlib.GaussianRealIntegral
import OperatorRidgelet.ToMathlib.GaussianTilt
import OperatorRidgelet.ToMathlib.GiryMonad
import OperatorRidgelet.ToMathlib.ComplexMeasurePolar
import OperatorRidgelet.ToMathlib.IntegralSqrt
import OperatorRidgelet.ToMathlib.Symmetrization
import OperatorRidgelet.ToMathlib.Logic
import OperatorRidgelet.ToMathlib.LpOfReal
import OperatorRidgelet.ToMathlib.MeasurePi
import OperatorRidgelet.ToMathlib.PolynomialCoeffBound
import OperatorRidgelet.ToMathlib.PolynomialGaussianDeriv
import OperatorRidgelet.ToMathlib.PolynomialGaussianSchwartz
import OperatorRidgelet.ToMathlib.PolynomialGrowthBounds
import OperatorRidgelet.ToMathlib.PositiveOperator
import OperatorRidgelet.ToMathlib.RpowIntegral
import OperatorRidgelet.ToMathlib.SchwartzFourier
import OperatorRidgelet.ToMathlib.StarProjectionBessel
import OperatorRidgelet.ToMathlib.TendstoUniformlyOnCompact
import OperatorRidgelet.ToMathlib.TraceClassEigenbasis
import OperatorRidgelet.ToMathlib.VectorMeasureMapDensity
import OperatorRidgelet.ToMathlib.VectorMeasureWithDensity
import OperatorRidgelet.Paper
import OperatorRidgelet.ArchitectBridge

/-!
# Operator ridgelet transform on infinite-dimensional Hilbert spaces

Lean formalization of the manuscript on the Gaussian-weighted ridgelet transform with
Hilbert-space inputs.  The statements of the manuscript are collected in `OperatorRidgelet.Paper`
and mirrored, with `sorry`, in the comparator challenge library `Challenge`.
-/
