#!/usr/bin/env python3
"""Generate STATUS.md: which manuscript statements are formalized and which are verified.

Sources: `comparator/paper.json` (manuscript items and their Lean names), `Challenge/` (statement
formalized), `comparator/config.json` `theorem_names` (verified by comparator), the `sorry`
occurrences in `OperatorRidgelet/Paper/`, and the `notReady` flags in `ArchitectBridge.lean`.
Writes to stdout; the Makefile-free convention is `scripts/status.py > ../STATUS.md`.
"""
from __future__ import annotations
import json, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from leanparse import parse_tree, strip_comments  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
NOTREADY_RE = re.compile(r"attribute \[blueprint \"(?P<label>[^\"]+)\"(?P<opts>.*?)\]\s*(?P<name>[\w.']+)", re.S)


def main() -> int:
    paper = json.loads((ROOT / "comparator" / "paper.json").read_text())
    config = json.loads((ROOT / "comparator" / "config.json").read_text())
    verified = set(config["theorem_names"])
    challenge = parse_tree(ROOT / "Challenge", ROOT / "Challenge.lean")
    solution = parse_tree(ROOT / "OperatorRidgelet" / "Paper", ROOT / "OperatorRidgelet" / "Paper.lean")
    bridge = strip_comments((ROOT / "OperatorRidgelet" / "ArchitectBridge.lean").read_text())
    not_ready = {m.group("name") for m in NOTREADY_RE.finditer(bridge) if "notReady := true" in m.group("opts")}
    tagged = {m.group("name") for m in NOTREADY_RE.finditer(bridge)}

    warnings: list[str] = []
    for n in sorted(verified):
        if n not in solution:
            warnings.append(f"`{n}` is in theorem_names but not declared in OperatorRidgelet/Paper")
        if n not in challenge:
            warnings.append(f"`{n}` is in theorem_names but not declared in Challenge")
    for n, d in sorted(solution.items()):
        if d.kind not in ("theorem", "lemma"):
            continue
        proved = "sorry" not in d.body
        if proved and n not in verified:
            warnings.append(f"`{n}` has no `sorry` but is not in theorem_names (add it and run comparator)")
        if not proved and n in verified:
            warnings.append(f"`{n}` contains `sorry` but is in theorem_names")
        if n in tagged and (n in not_ready) != (not proved):
            warnings.append(f"`{n}`: notReady flag in ArchitectBridge disagrees with its `sorry` status")

    rows, n_stated, n_proved, n_partial = [], 0, 0, 0
    for it in paper["items"]:
        names = it.get("lean", [])
        stated = bool(names) and all(n in challenge for n in names)
        proved_n = sum(1 for n in names if n in verified)
        if stated:
            n_stated += 1
        if names and proved_n == len(names):
            n_proved += 1
        elif proved_n:
            n_partial += 1
        status = ("verified" if names and proved_n == len(names) else
                  f"partial {proved_n}/{len(names)}" if proved_n else
                  "stated" if stated else "—")
        rows.append((it["number"], it["label"], it["kind"], it["title"], names, status))

    total = len(paper["items"])
    ms = paper.get("manuscript", {})
    out = []
    out.append("# Formalization status\n")
    out.append(f"Manuscript `{ms.get('file', 'main.tex')}` at commit `{ms.get('commit', '?')}` "
               f"(numbers synced {ms.get('synced', '?')}). Generated by `scripts/status.py`; do not edit.\n")
    out.append(f"| Items | Statement formalized (in `Challenge`) | Proof verified by comparator | Partially verified |\n|---|---|---|---|\n"
               f"| {total} | {n_stated} | {n_proved} | {n_partial} |\n")
    out.append("`verified` means every Lean statement of the item is listed in `comparator/config.json` and "
               "passes `scripts/comparator-check.sh` (statement identical to `Challenge`, no `sorry`, only "
               "`propext`, `Quot.sound`, `Classical.choice`).\n")
    out.append("| No. | Label | Kind | Title | Lean | Status |\n|---|---|---|---|---|---|")
    for num, label, kind, title, names, status in rows:
        lean = "<br>".join(f"`{n}`" for n in names) if names else "—"
        out.append(f"| {num} | `{label}` | {kind} | {title} | {lean} | {status} |")
    if warnings:
        out.append("\n## Consistency warnings\n")
        out.extend(f"- {w}" for w in warnings)
    print("\n".join(out))
    return 1 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
