#!/usr/bin/env python3
"""Generate STATUS.md: which manuscript statements are formalized and which are verified.

Sources: `comparator/paper.json` (manuscript items and their Lean names), `Challenge/` (statement
formalized), `comparator/config.json` `theorem_names` (verified by comparator), the `sorry`
occurrences in `OperatorRidgelet/Paper/`, and the `notReady` flags in `ArchitectBridge.lean`.
Writes to stdout; the Makefile-free convention is `scripts/status.py > ../STATUS.md`.
"""
from __future__ import annotations
import json, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from leanparse import parse_tree, strip_comments  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
NOTREADY_RE = re.compile(r"attribute \[blueprint \"(?P<label>[^\"]+)\"(?P<opts>.*?)\]\s*(?P<name>[\w.']+)", re.S)


def main() -> int:
    paper = json.loads((ROOT / "comparator" / "paper.json").read_text())
    config = json.loads((ROOT / "comparator" / "config.json").read_text())
    verified = set(config["theorem_names"])
    challenge = parse_tree(ROOT / "Challenge", ROOT / "Challenge.lean")
    solution = parse_tree(ROOT / "OperatorRidgelet" / "Paper", ROOT / "OperatorRidgelet" / "Paper.lean")
    library = parse_tree(ROOT / "OperatorRidgelet")

    def is_stated(n: str) -> bool:
        """A theorem counts once it is in Challenge; a definition once it exists in the library."""
        if n in challenge:
            return True
        d = library.get(n)
        return d is not None and d.kind not in ("theorem", "lemma")

    def is_definition(n: str) -> bool:
        d = library.get(n)
        return d is not None and d.kind not in ("theorem", "lemma")
    bridge_root = ROOT / "OperatorRidgelet"
    bridge_files = [bridge_root / "ArchitectBridge.lean"]
    bridge_files.extend(sorted((bridge_root / "ArchitectBridge").rglob("*.lean")))
    bridge = "\n".join(strip_comments(path.read_text()) for path in bridge_files)
    not_ready = {m.group("name") for m in NOTREADY_RE.finditer(bridge) if "notReady := true" in m.group("opts")}
    tagged = {m.group("name") for m in NOTREADY_RE.finditer(bridge)}

    # Proofs that cite a still-`sorry` Paper theorem depend on `sorryAx` even when their own text
    # is `sorry`-free; propagate that to a fixed point so they are not reported as unregistered.
    sorry_dep = {n for n, d in solution.items() if d.kind in ("theorem", "lemma") and "sorry" in d.body}
    changed = True
    while changed:
        changed = False
        for n, d in solution.items():
            if n in sorry_dep or d.kind not in ("theorem", "lemma"):
                continue
            short = {m.rsplit(".", 1)[-1]: m for m in sorry_dep}
            if any(re.search(r"\b" + re.escape(k) + r"\b", d.body) for k in short):
                sorry_dep.add(n); changed = True

    warnings: list[str] = []
    for n in sorted(verified):
        if n not in solution:
            warnings.append(f"`{n}` is in theorem_names but not declared in OperatorRidgelet/Paper")
        if n not in challenge:
            warnings.append(f"`{n}` is in theorem_names but not declared in Challenge")
    for n, d in sorted(solution.items()):
        if d.kind not in ("theorem", "lemma"):
            continue
        proved = n not in sorry_dep
        if proved and n not in verified:
            warnings.append(f"`{n}` has no `sorry` but is not in theorem_names (add it and run comparator)")
        if not proved and n in verified:
            warnings.append(f"`{n}` contains `sorry` but is in theorem_names")
        if n in tagged and (n in not_ready) != (not proved):
            warnings.append(f"`{n}`: notReady flag in ArchitectBridge disagrees with its `sorry` status")

    rows, n_stated, n_proved, n_partial = [], 0, 0, 0
    for it in paper["items"]:
        names = it.get("lean", [])
        stated = bool(names) and all(is_stated(n) for n in names)
        thm_names = [n for n in names if not is_definition(n)]
        proved_n = sum(1 for n in thm_names if n in verified)
        if stated:
            n_stated += 1
        if names and stated and proved_n == len(thm_names):
            n_proved += 1
        elif proved_n:
            n_partial += 1
        status = ("defined" if names and stated and not thm_names else
                  "verified" if names and stated and proved_n == len(thm_names) else
                  f"partial {proved_n}/{len(thm_names)}" if proved_n else
                  "stated" if stated else "—")
        rows.append((it["number"], it["label"], it["kind"], it["title"], names, status))

    total = len(paper["items"])
    ms = paper.get("manuscript", {})
    out = []
    out.append("# Formalization status\n")
    out.append(f"Manuscript `{ms.get('file', 'main.tex')}`, version {ms.get('version', '?')} "
               f"(numbers synced {ms.get('synced', '?')}). Generated by `scripts/status.py`; do not edit.\n")
    out.append(f"| Items | Stated (theorem in `Challenge`, or definition in the library) | Verified by comparator (or pure definition) | Partially verified |\n|---|---|---|---|\n"
               f"| {total} | {n_stated} | {n_proved} | {n_partial} |\n")
    out.append("`verified` means every Lean statement of the item is listed in `comparator/config.json` and "
               "passes `scripts/comparator-check.sh` (statement identical to `Challenge`, no `sorry`, only "
               "`propext`, `Quot.sound`, `Classical.choice`).\n")
    out.append("| No. | Label | Kind | Title | Lean | Status |\n|---|---|---|---|---|---|")
    for num, label, kind, title, names, status in rows:
        lean = "<br>".join(f"`{n}`" for n in names) if names else "—"
        out.append(f"| {num} | `{label}` | {kind} | {title} | {lean} | {status} |")
    if warnings:
        out.append("\n## Consistency warnings\n")
        out.extend(f"- {w}" for w in warnings)
    print("\n".join(out))
    return 1 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
