import Verso
import VersoManual
import VersoBlueprint
import OperatorRidgelet.BasisIndependence
import OperatorRidgelet.Paper.Examples
import OperatorRidgelet.Paper.Networks
import OperatorRidgelet.Paper.Reconstruction
import OperatorRidgelet.Paper.Revision
import OperatorRidgelet.Paper.Sampling
import OperatorRidgelet.Paper.SamplingRevision
import OperatorRidgelet.Paper.Sobolev
import OperatorRidgelet.Paper.Tempered
import OperatorRidgelet.Paper.Transform
import OperatorRidgelet.ToMathlib.VectorMeasureRadonNikodym
import OperatorRidgelet.Transform.Infra

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option verso.blueprint.externalCode.strictResolve true

#doc (Manual) "Neural networks with Hilbert-space inputs" =>
%%%
file := "networks"
%%%

A network measures its input through inner products and applies a scalar activation to
those measurements. The input space $`H` is a separable real Hilbert space; the output
space $`Y` is a separable complex Hilbert space. Approximation is measured uniformly on
compact input sets. Finite-width networks are obtained by sampling an integral network.

The statements below use the bias coordinate $`c=-b`, so that a manuscript neuron
$`\sigma(\langle a,x\rangle-b)` is written $`\beta(\langle a,x\rangle+c)`.
This coordinate choice agrees with the Lean statements and leaves the represented networks unchanged.

# Finite-width and integral networks

The finite sum and the integral representation use the same atoms. In the vector-valued
case the coefficient measure has bounded variation, and integration is understood in the
Bochner sense.

:::definition "def:2.1" (lean := "OperatorRidgelet.finiteNetwork")
For a continuous activation $`\beta:\mathbb R\to\mathbb C`, a width-$`N` network on $`H` with
values in $`Y` is $`f_N(x)=\sum_{j=1}^Nv_j\,\beta(\langle a_j,x\rangle+c_j)` with outer weights
$`v_j\in Y` and parameters $`(a_j,c_j)\in H\times\mathbb R`; the scalar case is $`Y=\mathbb C`.
Approximation is measured in the compact-open topology of $`C(H;Y)`, generated by the seminorms
$`\|f\|_{C(K;Y)}=\sup_{x\in K}\|f(x)\|_Y` over compact $`K\subset H`.
:::

:::definition "def:2.2" (lean := "OperatorRidgelet.integralNetwork, OperatorRidgelet.totalVariation, OperatorRidgelet.integralNetworkDensity, OperatorRidgelet.Paper.def_2_2_i, OperatorRidgelet.Paper.def_2_2_ii")
Let $`\Gamma` be a $`Y`-valued Borel measure of bounded variation on $`\Theta=H\times\mathbb R`
with variation $`|\Gamma|` and total variation $`\|\Gamma\|_{\mathrm{TV}}=|\Gamma|(\Theta)`.
Whenever the Bochner integral exists, the integral network is
$`S_\beta[\Gamma](x)=\int_{H\times\mathbb R}\beta(\langle a,x\rangle+c)\,\Gamma(\mathrm da,\mathrm dc)`;
if $`\beta` is globally Lipschitz, it suffices that
$`\int(1+\|a\|+|c|)\,\mathrm d|\Gamma|<\infty` (part i). When $`\Gamma=\gamma\lambda` has a
density $`\gamma` with respect to a $`\sigma`-finite reference measure $`\lambda`, the network is
also written $`S_\beta[\gamma]` and computed as the Bochner integral of
$`\beta(\langle a,x\rangle+c)\gamma(a,c)` against $`\lambda` (part ii).
:::
