#!/usr/bin/env python3

"""Regenerate the badge block of README.md from the pinned Lean toolchain.

The lines between ``<!-- BEGIN GENERATED BADGES -->`` and ``<!-- END GENERATED BADGES -->`` in
README.md are generated by this script; edit the badges here, not in the README.  The Lean
version is read from ``OperatorRidgelet/lean-toolchain``, which must agree with
``OperatorRidgeletBlueprint/lean-toolchain``.  ``--check`` exits 1 instead of writing when the
README is stale; ``.github/workflows/badges.yml`` runs it on every push and pull request.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

START = "<!-- BEGIN GENERATED BADGES -->"
END = "<!-- END GENERATED BADGES -->"
REPOSITORY = "shosonoda/lean-operator-ridgelet"
PAGES_URL = "https://shosonoda.github.io/lean-operator-ridgelet/"
TOOLCHAINS = ("OperatorRidgelet/lean-toolchain", "OperatorRidgeletBlueprint/lean-toolchain")


def lean_version(repo_root: Path) -> str:
    """The Lean version pinned by both projects, e.g. ``4.32.0``."""
    contents = {name: (repo_root / name).read_text(encoding="utf-8").strip() for name in TOOLCHAINS}
    values = set(contents.values())
    if len(values) != 1:
        listing = ", ".join(f"{name}: {value!r}" for name, value in contents.items())
        raise ValueError(f"the lean-toolchain files disagree ({listing})")
    toolchain = contents[TOOLCHAINS[0]]
    marker = ":v"
    if marker not in toolchain:
        raise ValueError(f"unsupported lean-toolchain value: {toolchain!r}")
    version = toolchain.rsplit(marker, 1)[1]
    if not version:
        raise ValueError(f"{TOOLCHAINS[0]} does not contain a version")
    return version


def shields_text(text: str) -> str:
    """Escape ``text`` for a static shields.io badge path (``-`` and ``_`` are separators)."""
    return text.replace("-", "--").replace("_", "__")


def badge_block(version: str) -> str:
    """The generated Markdown block, markers included."""
    pages_workflow = f"https://github.com/{REPOSITORY}/actions/workflows/pages.yml"
    pages_status = (
        f"https://img.shields.io/github/actions/workflow/status/{REPOSITORY}/pages.yml"
        "?branch=main&label=blueprint%20pages&style=flat-square"
    )
    badges = [
        (
            f"Lean {version}",
            f"https://img.shields.io/badge/Lean-{shields_text(version)}-0f4c81.svg?style=flat-square",
            "https://lean-lang.org/",
        ),
        (
            "Blueprint",
            "https://img.shields.io/badge/blueprint-Verso-6f42c1.svg?style=flat-square",
            PAGES_URL,
        ),
        ("Blueprint pages", pages_status, pages_workflow),
        (
            "License Apache-2.0",
            "https://img.shields.io/badge/license-Apache--2.0-blue.svg?style=flat-square",
            "LICENSE",
        ),
    ]
    lines = [f"[![{alt}]({image})]({link})" for alt, image, link in badges]
    return "\n".join([START, *lines, END])


def updated_readme(path: Path, block: str) -> str:
    document = path.read_text(encoding="utf-8")
    if document.count(START) != 1 or document.count(END) != 1:
        raise ValueError(f"expected exactly one generated badge block in {path}")
    prefix, remainder = document.split(START, 1)
    _, suffix = remainder.split(END, 1)
    return prefix + block + suffix


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail instead of writing when README.md is stale"
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    readme = repo_root / "README.md"
    try:
        expected = updated_readme(readme, badge_block(lean_version(repo_root)))
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if expected == readme.read_text(encoding="utf-8"):
        return 0
    if args.check:
        print("README.md badge block is stale; run: python3 scripts/update-readme-badges.py")
        return 1
    readme.write_text(expected, encoding="utf-8")
    print(f"updated {readme.relative_to(repo_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
